rss_groups:
  技术: &tech
    美团技术团队: https://tech.meituan.com/feed/
  知识: &knownledge
    知乎日报: https://www.zhihu.com/rss

chat_ids:
  383054885:
    <<: *tech
    <<: *knownledge
    月光博客: https://www.williamlong.info/rss.xml